apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: python-app-green
images:
- name: hello-gitops
  newName: pratikkhan79/hello-gitops
  newTag: 8d8a6e9ca370094688900b4a36b0a0bc188874dd
